server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ua-hannam/config-registry.git
          default-label: main
          ignoreLocalSshSettings: true
          strictHostKeyChecking: false
          host-key:
          host-key-algorithm: ecdsa-sha2-nistp256
          private-key:

          passphrase: