server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ua-hannam/config-registry.git
          default-label: main
          ignoreLocalSshSettings: true
          strictHostKeyChecking: false
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEcZlBA5vO7VfsJy8AYZoT8/ulowCeWi81Gs9u1h2ckBQx++Rt2/qcF5j8tZYD24h0HsELLKJ5ryEeqCOJ28ypc= minjae@minjae-HP-ProDesk-600-G2-DM
          host-key-algorithm: ecdsa-sha2-nistp256
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIEnjDgJ8OYEX3h4h3NUX6gOqlH2FLv7S/wYXtShOmzmeoAoGCCqGSM49
            AwEHoUQDQgAERxmUEDm87tV+wnLwBhmhPz+6WjAJ5aLzUaz27WHZyQFDH75G3b+p
            wXmPy1lgPbiHQewQssonmvIR6oI4nbzKlw==
            -----END EC PRIVATE KEY-----
          passphrase: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEcZlBA5vO7VfsJy8AYZoT8/ulowCeWi81Gs9u1h2ckBQx++Rt2/qcF5j8tZYD24h0HsELLKJ5ryEeqCOJ28ypc= minjae@minjae-HP-ProDesk-600-G2-DM